name: "Atmos GitOps Select Components"
description: "A GitHub Action to get list of selected components by jq query"
author: hello@cloudposse.com
branding:
  icon: "file"
  color: "white"
inputs:
  jq-query:
    description: jq query that will be used to select atmos components
    required: true
  default-branch:
    description: The default branch to use for the base ref.
    required: false
    default: ${{ github.event.repository.default_branch }}
  install-atmos:
    description: Whether to install atmos
    required: false
    default: "true"
  atmos-version:
    description: The version of atmos to install if install-atmos is true
    required: false
    default: "latest"
  atmos-config-path:
    description: The path to the atmos.yaml file
    required: false
    default: atmos.yaml
  install-terraform:
    description: Whether to install terraform
    required: false
    default: "true"
  terraform-version:
    description: The version of terraform to install if install-terraform is true
    required: false
    default: "latest"
  install-jq:
    description: Whether to install jq
    required: false
    default: "false"
  jq-version:
    description: The version of jq to install if install-jq is true
    required: false
    default: "1.6"
  jq-force:
    description: Whether to force the installation of jq
    required: false
    default: "true"
  debug:
    description: "Enable action debug mode. Default: 'false'"
    default: 'false'
    required: false
outputs:
  selected-components:
    description: Selected GitOps components
    value: ${{ steps.selected-components.outputs.components }}
  matrix:
    description: Matrix for Selected GitOps components
    value: ${{ steps.matrix.outputs.matrix }}
  has-selected-components:
    description: Whether there are selected components
    value: ${{ steps.selected-components.outputs.components != '[]' }}

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.install-terraform == 'true' }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - if: ${{ inputs.install-atmos == 'true' }}
      uses: cloudposse/github-action-setup-atmos@v1.0.0
      env:
       ATMOS_CLI_CONFIG_PATH: ${{inputs.atmos-config-path}}
      with:
        atmos-version: ${{ inputs.atmos-version }}
        install-wrapper: false

    - if: ${{ inputs.install-jq == 'true' }}
      uses: dcarbone/install-jq-action@v1.0.1
      with:
        version: ${{ inputs.jq-version }}
        force: ${{ inputs.jq-force }}

    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.default-branch }}

    - name: atmos get selected components
      id: selected-components
      shell: bash
      env:
        ATMOS_CLI_CONFIG_PATH: ${{inputs.atmos-config-path}}
      run: |
        JQ_QUERY='${{ inputs.jq-query }}' DEBUG="${{ inputs.debug }}" ${{ github.action_path }}/src/filter.sh

        components=$(cat components.json)
        echo "Selected components: $components"
        printf "%s" "components=$components" >> $GITHUB_OUTPUT

    - name: build matrix
      id: matrix
      shell: bash
      run: |
        matrix=$(jq -c '{include:[.[]]}' < components.json)
        echo "matrix=$matrix" >> $GITHUB_OUTPUT
        [[ "${{ inputs.debug }}" == "true" ]] && echo "$matrix"