name: "Atmos GitOps Select Components"
description: "A GitHub Action to get list of selected components by jq query"
author: hello@cloudposse.com
branding:
  icon: "file"
  color: "white"
inputs:
  select-filter:
    description: jq query that will be used to select atmos components
    required: false
    default: '.'
  head-ref:
    description: The head ref to checkout. If not provided, the head default branch is used.
    required: false
    default: ${{ github.sha }}
  atmos-version:
    description: The version of atmos to install
    required: false
    default: ">= 1.63.0"
  atmos-config-path:
    description: The path to the atmos.yaml file
    required: true
  jq-version:
    description: The version of jq to install if install-jq is true
    required: false
    default: "1.6"
  debug:
    description: "Enable action debug mode. Default: 'false'"
    default: 'false'
    required: false
  nested-matrices-count:
    required: false
    description: 'Number of nested matrices that should be returned as the output (from 1 to 3)'
    default: "2"
outputs:
  selected-components:
    description: Selected GitOps components
    value: ${{ steps.selected-components.outputs.components }}
  has-selected-components:
    description: Whether there are selected components
    value: ${{ steps.selected-components.outputs.components != '[]' }}
  matrix:
    description: The selected components as matrix structure suitable for extending matrix size workaround (see README)
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.head-ref }}

    - name: Install JQ
      uses: dcarbone/install-jq-action@v1.0.1
      with:
        version: ${{ inputs.jq-version }}

    - name: Install Atmos
      uses: cloudposse/github-action-setup-atmos@v1
      with:
        atmos-version: ${{ inputs.atmos-version }}
        install-wrapper: false

    - name: Set vars
      shell: bash
      run: |-
        echo "ATMOS_CLI_CONFIG_PATH=$(realpath ${{ inputs.atmos-config-path }})" >> $GITHUB_ENV 

    - name: config
      shell: bash
      id: config
      run: |-
        echo "group-by=$(atmos describe config -f json | jq -r '.integrations.github.gitops.matrix["group-by"]')" >> $GITHUB_OUTPUT
        echo "sort-by=$(atmos describe config -f json | jq -r '.integrations.github.gitops.matrix["sort-by"]')" >> $GITHUB_OUTPUT        

    - name: Filter Components
      id: selected-components
      shell: bash
      env:
        ATMOS_CLI_CONFIG_PATH:  ${{ steps.config.outputs.atmos-config-path }}
        JQUERY: |
          with_entries(.value |= (.components.terraform)) |             ## Deal with components type of terraform
          map_values(map_values(select(${{ inputs.select-filter }}))) | ## Filter components by enabled github actions
          map_values(select(. != {})) |                                 ## Skip stacks that have 0 selected components
          map_values(. | keys) |                                        ## Reduce to component names
          with_entries(                                                 ## Construct component object
            .key as $stack | 
            .value |= map({
              "component": ., 
              "stack": $stack, 
              "stack_slug": [$stack, .] | join("-")
            })
          ) | map(.) | flatten                                          ## Reduce to flat array
      run: |
        atmos describe stacks --format json | jq -ce "${JQUERY}" > components.json

        components=$(cat components.json)
        echo "Selected components: $components"
        printf "%s" "components=$components" >> $GITHUB_OUTPUT

    - uses: cloudposse/github-action-matrix-extended@v0
      id: matrix
      with:
        matrix: components.json
        sort-by: ${{ steps.config.outputs.sort-by }}
        group-by: ${{ steps.config.outputs.group-by }}
        nested-matrices-count: ${{ inputs.nested-matrices-count }}
