on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - uses: cloudposse/github-action-setup-atmos@v1.0.0
        with:
          atmos-version: "latest"

      - uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: "1.6"

      - name: Run Tests
        run: ./test/run.sh
